# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nextlevellearning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "19.x"

      - name: Generate json pages
        run: |
          bash src/app/content/getJsonFiles.sh

      - name: npm install, build, and test
        run: |
          yarn install
          CI=false npm run build --if-present
          npm run test --if-present

      - name: "Cleanup build folder"
        run: |
          rm -rf ./next/cache

      - name: Zip artifact for deployment
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        run: zip release.zip ./* .next .env -qr

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "nextlevellearning"
          slot-name: "Production"
          package: release.zip

      # Azure logout
      - name: logout
        run: |
          az logout
